version: '3'
services:
  server:
    build: ./frauddetect
    expose:
      - 8080
    ports:
      - 8080:8080
    command: npm start
    networks:
      gateway:
        ipv4_address: 172.20.0.2

  client:
    build: ./fd_fe
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - server
    command: npm start
    networks:
      gateway:
        ipv4_address: 172.20.0.3

networks:
  gateway:
    ipam:
      config:
        - subnet: 172.20.0.0/24